/**
 * @fileoverview Core business logic and shared types for Calypso PRD Wizard.
 * Adheres to the "single source of truth" principle for data models.
 */

/**
 * Business Unit Domains
 * Categories of enterprise departments that the wizard discovers.
 */
export type BusinessUnitDomain = 'Sales' | 'HR' | 'Engineering' | 'Operations' | 'Finance' | 'Legal' | 'Marketing';

export interface BusinessUnit {
    id: string;
    domain: BusinessUnitDomain;
    description: string;
    keyStakeholders: string[];
}

/**
 * Data Interaction Mapping
 * Defines how data flows between units or external services.
 */
export interface DataFlow {
    id: string;
    source: string;
    sink: string;
    dataType: string;
    frequency: 'real-time' | 'daily' | 'on-demand';
}

/**
 * Agent Governance Rules
 * Defines the AI agent's access level to specific sensitive data.
 */
export interface AgentGovernanceRule {
    dataType: string;
    permission: 'query' | 'fuse' | 'blocked';
    justification: string;
}

/**
 * Canonical PRD Schema
 * The complete data structure generated by the wizard.
 */
export interface PRDSchema {
    projectName: string;
    vision: string;
    units: BusinessUnit[];
    flows: DataFlow[];
    governance: AgentGovernanceRule[];
    requirements: string[]; // High-level operational requirements
    version: string;
    updatedAt: string;
}

/**
 * Wizard State Machine Types
 * Used by the frontend WizardStore to manage progression.
 */
export type WizardStep = 'Discovery' | 'Mapping' | 'Governance' | 'Review' | 'Complete';

export interface WizardState {
    currentStep: WizardStep;
    data: PRDSchema;
    isGenerating: boolean;
}

